services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    ports:
      - 32400:32400
    volumes:
      - /home/sjohnson/media/storage/Configs:/config
      - /home/sjohnson/media/storage/TV:/TV
      - /home/sjohnson/media/storage/Movies:/Movies
    restart: unless-stopped
    networks:
      - network
    
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/sjohnson/media/storage/Configs/Jackett:/config
      - /home/sjohnson/media/storage/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - network
    
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
        - 90:80
    volumes:
        - /home/sjohnson/media/storage/Configs/Organizr:/config
    environment:
        - fpm=true
        - branch=v2-master
        - PUID=1000
        - PGID=1000
        - TZ=America/Toronto
    networks:
      - network
    
  qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT_ENV=8080
      - INCOMING_PORT_ENV=8999
      - VPN_ENABLED=yes
      - LAN_NETWORK=10.0.0.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /home/sjohnson/media/storage/Configs/QBittorrentVPN:/config
      - /home/sjohnson/media/storage/Torrents:/downloads
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - network
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022
    volumes:
      - /home/sjohnson/media/storage/Configs/Radarr:/config
      - /home/sjohnson/media/storage/Downloads:/downloads
      - /home/sjohnson/media/storage/Movies:/Movies
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - network
    
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/sjohnson/media/storage/Configs/Sabnzbd:/config
      - /home/sjohnson/media/storage/Downloads:/downloads
      - /home/sjohnson/media/storage/Downloads/Incomplete:/incomplete-downloads
    ports:
      - 8181:8080
      - 9191:9090
    restart: unless-stopped
    networks:
      - network
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - UMASK_SET=022
    volumes:
      - /home/sjohnson/media/storage/Configs/Sonarr:/config
      - /home/sjohnson/media/storage/Downloads:/downloads
      - /home/sjohnson/media/storage/TV:/TV
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - network

networks:
  network:
    name: my-bridge-network
    external: true